spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tiansong999/springcloud
          search-paths: respo
          username:
          password:
        default-label: master

  application:
    name: config-server
server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/

