server:
  port: 8762
eureka:
  instance:
    hostname: erueka02
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8763/eureka/
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: springcloud_erueka
