server:
  port: 8761
eureka:
  instance:
    hostname: erueka01
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: springcloud_erueka
